[project]
name = "dishboard"
description = "Distributed Interactive Simulation (DIS) Dashboard"
dynamic = ["version"]
readme = "docs/source/index.rst"
requires-python = ">=3.11.10"
license = "LGPL-2.1-or-later"

dependencies = [
    "Django>=6.0",
    "django-htmx",
    "django-tasks-db",
    "opendis",
    "altair",
    "pandas",
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "furo",
    "sphinx-needs",
    "sphinx-codelinks",
    "sphinx-autoapi",
]
build = [
    "lxml",
]

[tool.hatch.version]
path = "src/__init__.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pdu-generator]
path = "hatch_build.py"

[tool.hatch.build.targets.sdist]
include = [
    "src/",
]

