name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install dependencies
        run: |
          pip install .[docs]

      - name: Build HTML docs
        run: sphinx-build -b html docs/source docs/build/html

      - name: Build LaTeX docs
        run: sphinx-build -b latex docs/source docs/build/latex

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: dishboard.tex
          working_directory: docs/build/latex



